### ISSUE TITLE
What's wrong??

### ISSUE THREAD

**Issue by Abdalfattahaktaa** [Itz-fork/Mega.nz-Bot#23]
2022-03-26T14:41:29.425138+00:00 heroku[worker.1]: State changed from starting to up
2022-03-26T14:41:30.040801+00:00 app[worker.1]: 
2022-03-26T14:41:30.040814+00:00 app[worker.1]:    __  ___                                     ___       __ 
2022-03-26T14:41:30.040815+00:00 app[worker.1]:   /  |/  /__ ___ ____ _      ___  ___   ____  / _ )___  / /_
2022-03-26T14:41:30.040815+00:00 app[worker.1]:  / /|_/ / -_) _ `/ _ `/ _   / _ \/_ /  /___/ / _  / _ \/ __/
2022-03-26T14:41:30.040815+00:00 app[worker.1]: /_/  /_/\__/\_, /\_,_/ (_) /_//_//__/       /____/\___/\__/ 
2022-03-26T14:41:30.040816+00:00 app[worker.1]:            /___/
2022-03-26T14:41:30.040816+00:00 app[worker.1]: 
2022-03-26T14:41:30.040816+00:00 app[worker.1]: Process: Your Mega.nz-Bot is Starting! Please Wait...
2022-03-26T14:41:30.040820+00:00 app[worker.1]: 
2022-03-26T14:41:34.376477+00:00 app[worker.1]: Traceback (most recent call last):
2022-03-26T14:41:34.376497+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2022-03-26T14:41:34.376593+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2022-03-26T14:41:34.376594+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/runpy.py", line 86, in _run_code
2022-03-26T14:41:34.376671+00:00 app[worker.1]:     exec(code, run_globals)
2022-03-26T14:41:34.376674+00:00 app[worker.1]:   File "/app/megadl/__main__.py", line 15, in <module>
2022-03-26T14:41:34.376732+00:00 app[worker.1]:     meganzbot.start()
2022-03-26T14:41:34.376740+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
2022-03-26T14:41:34.376812+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2022-03-26T14:41:34.376819+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
2022-03-26T14:41:34.376977+00:00 app[worker.1]:     return future.result()
2022-03-26T14:41:34.376985+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 67, in start
2022-03-26T14:41:34.377056+00:00 app[worker.1]:     await self.initialize()
2022-03-26T14:41:34.377063+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2022-03-26T14:41:34.377137+00:00 app[worker.1]:     self.load_plugins()
2022-03-26T14:41:34.377144+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/client.py", line 720, in load_plugins
2022-03-26T14:41:34.377304+00:00 app[worker.1]:     module = import_module(module_path)
2022-03-26T14:41:34.377311+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-03-26T14:41:34.377382+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2022-03-26T14:41:34.377389+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-03-26T14:41:34.377458+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-03-26T14:41:34.377498+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2022-03-26T14:41:34.377536+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-03-26T14:41:34.377575+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-03-26T14:41:34.377619+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-03-26T14:41:34.377658+00:00 app[worker.1]:   File "/app/megadl/modules/callbacks.py", line 9, in <module>
2022-03-26T14:41:34.377732+00:00 app[worker.1]:     from .mega_dl import basedir
2022-03-26T14:41:34.377739+00:00 app[worker.1]:   File "/app/megadl/modules/mega_dl.py", line 11, in <module>
2022-03-26T14:41:34.377815+00:00 app[worker.1]:     from fsplit.filesplit import Filesplit
2022-03-26T14:41:34.377844+00:00 app[worker.1]: ModuleNotFoundError: No module named 'fsplit'
2022-03-26T14:41:34.603762+00:00 heroku[worker.1]: Process exited with status 1
2022-03-26T14:41:34.681526+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by Itz-fork** [comment]
Deploy the latest version
