### ISSUE TITLE
AttributeError: The API key is required for new authorizations.

### ISSUE THREAD

**Issue by forbot002** [Itz-fork/Mega.nz-Bot#32]
Hi,

I'm trying to deploy this bot in termux android.
but I receiving this error?
I would appreciate it if you could help me with this problem?

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/home/Mega.nz-Bot/megadl/__main__.py", line 18, in <module>
    meganzbot.start()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/client.py", line 575, in load_session
    raise AttributeError("The API key is required for new authorizations. "
AttributeError: The API key is required for new authorizations. More info: https://docs.pyrogram.org/start/auth
```

### Edit:
I did `cp config.sample config.env` and fill every line

**Comment by Itz-fork** [comment]
> ### Edit:
> I did `cp config.sample config.env` and fill every line

But why? You should just do,

```
cat config.sample > config.py
nano config.py
```

**Comment by forbot002** [comment]
> > ### Edit:
> > I did `cp config.sample config.env`
> 
> But why? You should just do,
> 
> ```
> cat config.sample > config.py
> nano config.py
> ```


Sorry I thought that it had be done like that
 my bad.
 I Thank you for your answer.
