### ISSUE TITLE
Key Error : 0

### ISSUE THREAD

**Issue by Falcon87262** [Itz-fork/Mega.nz-Bot#37]
hi 
i am having this problem using ubuntu on wsl windows 10

Process: Your Mega.nz-Bot is Starting! Please Wait...

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/d/Mega/Mega.nz-Bot/megadl/__main__.py", line 18, in <module>
    meganzbot.start()
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/client.py", line 584, in load_session
    await Auth(
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/session/auth.py", line 254, in create
    raise e
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/session/auth.py", line 89, in create
    res_pq = await self.invoke(raw.functions.ReqPqMulti(nonce=nonce))
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/session/auth.py", line 67, in invoke
    return self.unpack(response)
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/session/auth.py", line 60, in unpack
    return TLObject.read(b)
  File "/mnt/d/Mega/ve/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
KeyError: 0

i am new at this and dont know what the problem is.
do take a look at it plz

**Comment by Itz-fork** [comment]
Closing since new version doesn't use mega.py anymore
