### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by Prime-Hritu** [Itz-fork/Mega.nz-Bot#49]
[MegaBotCypher] No plugin loaded from "megadl/modules"

**Comment by Prime-Hritu** [comment]
how to solve ?

**Comment by Prime-Hritu** [comment]
'NoneType' object has no attribute 'id'
2024-01-10T02:45:11.486119+00:00 app[worker.1]: Traceback (most recent call last):
2024-01-10T02:45:11.486121+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2024-01-10T02:45:11.486121+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2024-01-10T02:45:11.486122+00:00 app[worker.1]:   File "/app/megadl/helpers/cypher.py", line 133, in cy_run
2024-01-10T02:45:11.486123+00:00 app[worker.1]:     uid = msg.from_user.id
2024-01-10T02:45:11.486124+00:00 app[worker.1]:           ^^^^^^^^^^^^^^^^
2024-01-10T02:45:11.486124+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Itz-fork** [comment]
> [MegaBotCypher] No plugin loaded from "megadl/modules"

You can ignore this as this doesn't affect bot's functionality

> 'NoneType' object has no attribute 'id' 2024-01-10T02:45:11.486119+00:00 app[worker.1]: Traceback (most recent call last): 2024-01-10T02:45:11.486121+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker 2024-01-10T02:45:11.486121+00:00 app[worker.1]: await handler.callback(self.client, *args) 2024-01-10T02:45:11.486122+00:00 app[worker.1]: File "/app/megadl/helpers/cypher.py", line 133, in cy_run 2024-01-10T02:45:11.486123+00:00 app[worker.1]: uid = msg.from_user.id 2024-01-10T02:45:11.486124+00:00 app[worker.1]: ^^^^^^^^^^^^^^^^ 2024-01-10T02:45:11.486124+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'id'

Could you provide more details about how this error occurred?

**Comment by Itz-fork** [comment]
No activity so closing this
